mansion_name: 'クレヴィア東陽町'
price: 0
adress: '江東区南砂'
station: '東陽町'
from_station: 3
floor_plan: '1LDK'
exclusive_area: 32
age: 11
stories: 5
direction: '東'
other_area: 5
total_rooms: 72
move_in_date: 0
reform: 0
ownership: '所有権'
use_district: '準住居'
url: 'aaa'
log_date: 20220129
service_room: 0